/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Usuario actual (RF01) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Me"];
                    };
                };
                401: components["responses"]["NoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de usuarios (admin, RF17) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Usuario"][];
                        };
                    };
                };
                403: components["responses"]["SinPermiso"];
            };
        };
        put?: never;
        /**
         * Alta de usuario (admin, RF17, RN11)
         * @description El usuario ya debe existir en Supabase Auth.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "email": "ana.perez@flota.example",
                     *       "nombre": "Ana Pérez",
                     *       "rol": "mantenimiento"
                     *     }
                     */
                    "application/json": components["schemas"]["UsuarioInput"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usuarios/{email}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                email: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Modifica nombre o rol (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    email: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        nombre?: string;
                        rol?: components["schemas"]["Rol"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/unidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Vista de flota (RF14)
         * @description Una fila por unidad con su estado resumido. `estado_mantenimiento` es el más crítico entre sus planes
         *     (vencida > proxima > postergada > al_dia) y es `null` si la unidad no tiene planes.
         *     Por defecto lista solo unidades activas; con `activa=false`, las dadas de baja.
         */
        get: {
            parameters: {
                query?: {
                    tenencia?: components["schemas"]["Tenencia"];
                    /** @description Filtra por estado de mantenimiento o por situación (fallas, dispositivo). */
                    estado?: "al_dia" | "proxima" | "vencida" | "postergada" | "con_fallas" | "sin_reportar" | "sin_dispositivo";
                    activa?: boolean;
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "data": [
                         *         {
                         *           "patente": "AP414XV",
                         *           "marca": "Scania",
                         *           "modelo": "P 360",
                         *           "anio": 2017,
                         *           "tenencia": "propia",
                         *           "titular": null,
                         *           "protocolo": "J1939",
                         *           "km_actual": 537033,
                         *           "km_fuente": "odometro",
                         *           "activa": true,
                         *           "estado_mantenimiento": "al_dia",
                         *           "fallas_activas": 0,
                         *           "dispositivo": {
                         *             "device_uid": "esp32-B4D43E",
                         *             "estado": "activo",
                         *             "ultima_comunicacion": "2026-10-07T14:46:00Z"
                         *           }
                         *         }
                         *       ],
                         *       "page": 1,
                         *       "page_size": 20,
                         *       "total": 21
                         *     }
                         */
                        "application/json": components["schemas"]["Pagina"] & {
                            data?: components["schemas"]["UnidadResumen"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /**
         * Alta de unidad (admin, RF02)
         * @description Nace con `km_actual = 0`, `km_fuente = manual` y sin planes ni dispositivo.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "patente": "AB123CD",
                     *       "marca": "Scania",
                     *       "modelo": "R 450",
                     *       "anio": 2021,
                     *       "tenencia": "fletero",
                     *       "titular": "Hugo Benítez",
                     *       "protocolo": "J1939"
                     *     }
                     */
                    "application/json": components["schemas"]["UnidadInput"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unidad"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /** Datos básicos de una unidad */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unidad"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        /**
         * Baja lógica (admin)
         * @description Marca `activa = false` y conserva el historial. Responde 409 si la unidad tiene un dispositivo vinculado.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unidad"];
                    };
                };
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        options?: never;
        head?: never;
        /** Modifica datos de la unidad (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnidadEdicion"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Unidad"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/unidades/{patente}/detalle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /**
         * Detalle consolidado de la unidad (RF15)
         * @description Unidad, dispositivo vigente, planes con su estado y fallas activas en una sola respuesta.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DetalleUnidad"];
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista de dispositivos con su unidad vinculada (admin, RF03) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Dispositivo"][];
                        };
                    };
                };
                403: components["responses"]["SinPermiso"];
            };
        };
        put?: never;
        /**
         * Alta de dispositivo (admin)
         * @description Nace con `estado = inactivo` y sin vincular.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @example esp32-0F3A21 */
                        device_uid: string;
                    };
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispositivo"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/dispositivos/{device_uid}/vincular": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example esp32-0F3A21 */
                device_uid: components["parameters"]["DeviceUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Vincula el dispositivo a una unidad (admin, RN02)
         * @description 409 si el dispositivo ya está vinculado o si la unidad ya tiene un dispositivo.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example esp32-0F3A21 */
                    device_uid: components["parameters"]["DeviceUid"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        patente: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispositivo"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        trace?: never;
    };
    "/dispositivos/{device_uid}/desvincular": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example esp32-0F3A21 */
                device_uid: components["parameters"]["DeviceUid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Desvincula el dispositivo de su unidad actual (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example esp32-0F3A21 */
                    device_uid: components["parameters"]["DeviceUid"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Dispositivo"];
                    };
                };
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        trace?: never;
    };
    "/tareas-catalogo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catálogo de tareas con sus intervalos por defecto (RF07, RN03) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["TareaCatalogo"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Alta de un tipo de tarea (admin) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "codigo": "FILTRO_AIRE",
                     *       "nombre": "Filtro de aire",
                     *       "intervalo_km_default": 80000,
                     *       "umbral_aviso_km_default": 4000
                     *     }
                     */
                    "application/json": components["schemas"]["TareaCatalogo"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TareaCatalogo"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}/planes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /** Planes de la unidad con su estado actual (RF07, RF08) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Plan"][];
                        };
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        /**
         * Asigna una tarea del catálogo a la unidad (admin)
         * @description `intervalo_km` y `umbral_aviso_km` toman el valor del catálogo si se omiten.
         *     `km_ultimo_service` es opcional; si se omite, el mock asume el km actual (decisión abierta).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "codigo_tarea": "ACEITE_MOTOR",
                     *       "intervalo_km": 60000,
                     *       "umbral_aviso_km": 4000
                     *     }
                     */
                    "application/json": components["schemas"]["PlanInput"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plan"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}/planes/{codigo_tarea}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
                /** @example ACEITE_MOTOR */
                codigo_tarea: components["parameters"]["CodigoTarea"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edita intervalo o umbral de un plan (admin) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                    /** @example ACEITE_MOTOR */
                    codigo_tarea: components["parameters"]["CodigoTarea"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        intervalo_km?: number;
                        umbral_aviso_km?: number;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Plan"];
                    };
                };
                400: components["responses"]["Validacion"];
                403: components["responses"]["SinPermiso"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/unidades/{patente}/services": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /**
         * Historial de services (RF16)
         * @description Más recientes primero. Filtra por período con `desde` y `hasta` (inclusivos).
         */
        get: {
            parameters: {
                query?: {
                    /** @description Fecha inicial inclusiva (YYYY-MM-DD) */
                    desde?: components["parameters"]["Desde"];
                    /** @description Fecha final inclusiva (YYYY-MM-DD) */
                    hasta?: components["parameters"]["Hasta"];
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pagina"] & {
                            data?: components["schemas"]["Service"][];
                        };
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        /**
         * Registra un service (RF09, RN06)
         * @description Reinicia `km_ultimo_service` de cada plan cubierto y cierra sus postergaciones abiertas.
         *     Si `km` supera el km actual de la unidad, lo actualiza. Un service por unidad y por día (409).
         *     400 si no hay tareas, si alguna no está en el plan de la unidad o si la fecha es futura.
         *     El usuario que lo registra sale del token.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "fecha": "2026-10-07",
                     *       "km": 412300,
                     *       "observaciones": "Sin novedades",
                     *       "tareas": [
                     *         "ACEITE_MOTOR",
                     *         "SECADOR_AIRE"
                     *       ]
                     *     }
                     */
                    "application/json": components["schemas"]["ServiceInput"];
                };
            };
            responses: {
                /** @description Creado */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Service"];
                    };
                };
                400: components["responses"]["Validacion"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}/postergaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /** Historial de postergaciones (RF16) */
        get: {
            parameters: {
                query?: {
                    /** @description Fecha inicial inclusiva (YYYY-MM-DD) */
                    desde?: components["parameters"]["Desde"];
                    /** @description Fecha final inclusiva (YYYY-MM-DD) */
                    hasta?: components["parameters"]["Hasta"];
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pagina"] & {
                            data?: components["schemas"]["Postergacion"][];
                        };
                    };
                };
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}/planes/{codigo_tarea}/postergaciones": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
                /** @example ACEITE_MOTOR */
                codigo_tarea: components["parameters"]["CodigoTarea"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Posterga una tarea (RF10, RN07)
         * @description 400 si `km_limite_nuevo` es menor o igual al km actual, o si el motivo es `otro` sin descripción.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                    /** @example ACEITE_MOTOR */
                    codigo_tarea: components["parameters"]["CodigoTarea"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "motivo": "otro",
                     *       "motivo_descripcion": "Esperando repuesto",
                     *       "km_limite_nuevo": 416000
                     *     }
                     */
                    "application/json": components["schemas"]["PostergacionInput"];
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Postergacion"];
                    };
                };
                400: components["responses"]["Validacion"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unidades/{patente}/fallas": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        /** Fallas de la unidad (RF11) */
        get: {
            parameters: {
                query?: {
                    estado?: "activo" | "inactivo";
                };
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data?: components["schemas"]["Falla"][];
                        };
                    };
                };
                400: components["responses"]["Validacion"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Alertas de todos los orígenes (RF13)
         * @description Ordenadas de la más antigua a la más reciente. Sin filtro de `estado` devuelve abiertas y revisadas.
         */
        get: {
            parameters: {
                query?: {
                    estado?: "abierta" | "revisada";
                    tipo?: components["schemas"]["TipoAlerta"];
                    patente?: string;
                    page?: components["parameters"]["Page"];
                    page_size?: components["parameters"]["PageSize"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Pagina"] & {
                            data?: components["schemas"]["Alerta"][];
                        };
                    };
                };
                400: components["responses"]["Validacion"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alertas/revisar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Marca una alerta como revisada (RF13)
         * @description El body es `{ origen, ...clave }`, donde `clave` es exactamente el objeto `clave` de la alerta listada.
         *     Es idempotente: revisar una alerta ya revisada devuelve 200 sin cambiar la fecha.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RevisarPlan"] | components["schemas"]["RevisarFalla"] | components["schemas"]["RevisarDispositivo"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Alerta"];
                    };
                };
                400: components["responses"]["Validacion"];
                404: components["responses"]["NoEncontrado"];
            };
        };
        trace?: never;
    };
    "/unidades/{patente}/kilometraje": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @example AB123CD */
                patente: components["parameters"]["Patente"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Carga manual de kilometraje (RF06, RN08, RN09)
         * @description Actualiza `km_actual` (fuente `manual`) y recalcula los planes. 409 si `km` es menor al actual.
         *     `fecha` es opcional (por defecto, ahora).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @example AB123CD */
                    patente: components["parameters"]["Patente"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "km": 415200
                     *     }
                     */
                    "application/json": {
                        km: number;
                        /** Format: date-time */
                        fecha?: string;
                    };
                };
            };
            responses: {
                /** @description Creada */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CargaKm"];
                    };
                };
                400: components["responses"]["Validacion"];
                404: components["responses"]["NoEncontrado"];
                409: components["responses"]["Conflicto"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        Pagina: {
            data: unknown[];
            page: number;
            page_size: number;
            total: number;
        };
        /** @enum {string} */
        Rol: "admin" | "mantenimiento";
        /** @enum {string} */
        Tenencia: "propia" | "fletero";
        /** @enum {string} */
        Protocolo: "J1939" | "J1979";
        /** @enum {string} */
        FuenteKm: "odometro" | "estimado" | "manual";
        /** @enum {string} */
        EstadoDispositivo: "activo" | "inactivo" | "sin_reportar";
        /** @enum {string} */
        EstadoPlan: "al_dia" | "proxima" | "vencida" | "postergada";
        /** @enum {string} */
        MotivoPostergacion: "falta_espacio" | "salida_urgente" | "otro";
        /** @enum {string} */
        TipoAlerta: "tarea_proxima" | "tarea_vencida" | "falla_nueva" | "dispositivo_sin_reportar";
        Me: {
            email?: string;
            nombre?: string | null;
            rol?: components["schemas"]["Rol"];
        };
        Usuario: {
            email?: string;
            nombre?: string | null;
            rol?: components["schemas"]["Rol"];
            /** Format: date-time */
            created_at?: string;
        };
        UsuarioInput: {
            email: string;
            nombre?: string;
            rol: components["schemas"]["Rol"];
        };
        Unidad: {
            patente?: string;
            marca?: string;
            modelo?: string | null;
            anio?: number | null;
            tenencia?: components["schemas"]["Tenencia"];
            /** @description Dueño de la unidad si es de un fletero */
            titular?: string | null;
            protocolo?: components["schemas"]["Protocolo"];
            km_actual?: number;
            km_fuente?: components["schemas"]["FuenteKm"];
            activa?: boolean;
            /** Format: date-time */
            created_at?: string;
        };
        UnidadInput: {
            patente: string;
            marca: string;
            modelo?: string;
            anio?: number;
            tenencia: components["schemas"]["Tenencia"];
            titular?: string;
            protocolo: components["schemas"]["Protocolo"];
        };
        UnidadEdicion: {
            marca?: string;
            modelo?: string;
            anio?: number;
            tenencia?: components["schemas"]["Tenencia"];
            titular?: string;
            protocolo?: components["schemas"]["Protocolo"];
        };
        /** @description Dispositivo vigente; `null` si la unidad no tiene ninguno. */
        DispositivoResumen: {
            device_uid?: string;
            estado?: components["schemas"]["EstadoDispositivo"];
            /** Format: date-time */
            ultima_comunicacion?: string | null;
        } | null;
        UnidadResumen: {
            patente?: string;
            marca?: string;
            modelo?: string | null;
            anio?: number | null;
            tenencia?: components["schemas"]["Tenencia"];
            titular?: string | null;
            protocolo?: components["schemas"]["Protocolo"];
            km_actual?: number;
            km_fuente?: components["schemas"]["FuenteKm"];
            activa?: boolean;
            /**
             * @description El más crítico entre sus planes; null si no tiene planes
             * @enum {string|null}
             */
            estado_mantenimiento?: "al_dia" | "proxima" | "vencida" | "postergada" | null;
            fallas_activas?: number;
            dispositivo?: components["schemas"]["DispositivoResumen"];
        };
        DetalleUnidad: {
            unidad?: components["schemas"]["Unidad"];
            /** @description Dispositivo vigente; null si la unidad no tiene ninguno. */
            dispositivo?: {
                device_uid?: string;
                estado?: components["schemas"]["EstadoDispositivo"];
                /** Format: date-time */
                ultima_comunicacion?: string | null;
                /**
                 * Format: date-time
                 * @description Inicio de la vinculación vigente
                 */
                desde?: string;
            } | null;
            planes?: components["schemas"]["Plan"][];
            fallas_activas?: components["schemas"]["Falla"][];
        };
        Dispositivo: {
            device_uid?: string;
            estado?: components["schemas"]["EstadoDispositivo"];
            /** Format: date-time */
            ultima_comunicacion?: string | null;
            /** Format: date-time */
            created_at?: string;
            vinculacion_actual?: {
                patente?: string;
                /** Format: date-time */
                desde?: string;
            } | null;
        };
        TareaCatalogo: {
            /** @example ACEITE_MOTOR */
            codigo: string;
            nombre: string;
            intervalo_km_default: number;
            /** @default 4000 */
            umbral_aviso_km_default: number;
        };
        PostergacionVigente: {
            /** Format: date-time */
            fecha?: string;
            motivo?: components["schemas"]["MotivoPostergacion"];
            motivo_descripcion?: string | null;
            km_limite_nuevo?: number;
            email_usuario?: string;
        } | null;
        Plan: {
            codigo_tarea?: string;
            nombre?: string;
            intervalo_km?: number;
            umbral_aviso_km?: number;
            km_ultimo_service?: number;
            /** @description Km en el que vence (último service + intervalo */
            km_limite?: number;
            /** @description km_limite - km actual de la unidad; negativo si ya se pasó */
            km_restantes?: number;
            estado?: components["schemas"]["EstadoPlan"];
            postergacion_vigente?: components["schemas"]["PostergacionVigente"];
        };
        PlanInput: {
            codigo_tarea: string;
            intervalo_km?: number;
            umbral_aviso_km?: number;
            km_ultimo_service?: number;
        };
        Service: {
            patente?: string;
            /** Format: date */
            fecha?: string;
            km?: number;
            observaciones?: string | null;
            email_usuario?: string;
            usuario_nombre?: string | null;
            tareas?: {
                codigo_tarea?: string;
                nombre?: string;
            }[];
        };
        ServiceInput: {
            /**
             * Format: date
             * @description Por defecto
             */
            fecha?: string;
            km: number;
            observaciones?: string;
            /** @description Códigos de tarea del plan de la unidad */
            tareas: string[];
        };
        Postergacion: {
            patente?: string;
            codigo_tarea?: string;
            tarea_nombre?: string;
            /** Format: date-time */
            fecha?: string;
            motivo?: components["schemas"]["MotivoPostergacion"];
            motivo_descripcion?: string | null;
            km_limite_nuevo?: number;
            email_usuario?: string;
            usuario_nombre?: string | null;
            /** @description true cuando un service posterior la cerró (RN06) */
            cerrada?: boolean;
        };
        PostergacionInput: {
            motivo: components["schemas"]["MotivoPostergacion"];
            /** @description Obligatoria si motivo = otro */
            motivo_descripcion?: string;
            km_limite_nuevo: number;
        };
        Falla: {
            /** @example SPN-100-FMI-3 */
            codigo?: string;
            /** Format: date-time */
            fecha_aparicion?: string;
            /** Format: date-time */
            fecha_cierre?: string | null;
            /**
             * @description activo mientras fecha_cierre sea null
             * @enum {string}
             */
            estado?: "activo" | "inactivo";
        };
        Alerta: {
            /** @enum {string} */
            origen?: "plan" | "falla" | "dispositivo";
            tipo?: components["schemas"]["TipoAlerta"];
            patente?: string | null;
            /** @description Código de tarea */
            referencia?: string;
            /** @description Nombre de la tarea (solo origen plan) */
            referencia_nombre?: string | null;
            /** Format: date-time */
            fecha_generada?: string;
            /** Format: date-time */
            fecha_revisada?: string | null;
            /** @enum {string} */
            estado?: "abierta" | "revisada";
            /** @description Identifica la alerta. Se reenvía tal cual, junto con `origen`, en PATCH /alertas/revisar. */
            clave?: {
                [key: string]: unknown;
            };
        };
        RevisarPlan: {
            /** @enum {string} */
            origen: "plan";
            patente: string;
            codigo_tarea: string;
            /** @enum {string} */
            tipo: "tarea_proxima" | "tarea_vencida";
            /** Format: date-time */
            fecha_generada: string;
        };
        RevisarFalla: {
            /** @enum {string} */
            origen: "falla";
            patente: string;
            codigo: string;
            /** Format: date-time */
            fecha_aparicion: string;
        };
        RevisarDispositivo: {
            /** @enum {string} */
            origen: "dispositivo";
            device_uid: string;
            /** Format: date-time */
            fecha_generada: string;
        };
        CargaKm: {
            patente?: string;
            /** Format: date-time */
            fecha?: string;
            km?: number;
            /** @enum {string} */
            fuente?: "manual";
            email_usuario?: string;
        };
    };
    responses: {
        /** @description Token ausente o inválido */
        NoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "no_autenticado",
                 *         "message": "Token inválido."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Rol insuficiente (RN11) */
        SinPermiso: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "sin_permiso",
                 *         "message": "Esta operación requiere rol admin (RN11)."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description No existe */
        NoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "no_encontrado",
                 *         "message": "No existe la unidad AB123CD."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Datos inválidos */
        Validacion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "validacion",
                 *         "message": "Faltan campos obligatorios: km."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description Conflicto con una regla de negocio */
        Conflicto: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "conflicto",
                 *         "message": "El kilometraje no puede disminuir (RN09): el actual es 415000."
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @example AB123CD */
        Patente: string;
        /** @example esp32-0F3A21 */
        DeviceUid: string;
        /** @example ACEITE_MOTOR */
        CodigoTarea: string;
        Page: number;
        PageSize: number;
        /** @description Fecha inicial inclusiva (YYYY-MM-DD) */
        Desde: string;
        /** @description Fecha final inclusiva (YYYY-MM-DD) */
        Hasta: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
